name: SHIPcal_demo
channels:
  - defaults
dependencies:
  - django=3.0.*
  - matplotlib=3.1.*
  - numpy=1.18.*
  - pandas=1.0.*
  - python=3.7.*
  - pip=20.1.*
  - scipy=1.4.*
  - pip:
    - django-countries==6.1.2
    - iapws==1.4.1

